import { Property, User, Inquiry, AuditLog, PlatformSettings } from "./types";

export const SAMPLE_USERS: User[] = [
  {
    id: "user-buyer-1",
    name: "Aarav Sharma",
    email: "buyer@landparcel.com",
    phone: "+91 98765 43210",
    role: "BUYER",
    password: "Password123!",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    bio: "High net-worth private investor seeking luxury penthouses and prime coastal villas in Mumbai and Goa.",
    isVerified: true,
    isBlocked: false,
    createdAt: new Date("2025-01-10").toISOString(),
  },
  {
    id: "user-agent-1",
    name: "Vikram Singhania",
    email: "agent@landparcel.com",
    phone: "+91 98200 12345",
    role: "AGENT",
    password: "Password123!",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    companyName: "Singhania Luxury Estates & Realty",
    licenseNumber: "RERA-MH-2023-884920",
    bio: "Specializing in ultra-luxury waterfront penthouses, gated golf communities, and prime residential developments across Mumbai & Goa with over 14 years of premier client advisory.",
    isVerified: true,
    isBlocked: false,
    createdAt: new Date("2024-11-15").toISOString(),
  },
  {
    id: "user-admin-1",
    name: "Priya Menon",
    email: "admin@landparcel.com",
    phone: "+91 99000 55555",
    role: "ADMIN",
    password: "Password123!",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
    bio: "Chief Executive Compliance Officer & Platform SuperAdministrator at LandParcel Realtors.",
    isVerified: true,
    isBlocked: false,
    createdAt: new Date("2024-01-01").toISOString(),
  },
];

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  commissionRate: 1.5,
  autoApproveVerifiedAgents: false,
  strictReraCompliance: true,
  maxFeaturedListings: 12,
  maintenanceMode: false,
  contactEmail: "concierge@landparcel.com",
  contactPhone: "+91 (022) 6789 0000",
};

export const SAMPLE_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    action: "APPROVE_PROPERTY",
    details: "Approved 'The Grand Azure Waterfront Penthouse' after title & RERA document verification.",
    targetType: "PROPERTY",
    targetId: "prop-1",
    adminName: "Priya Menon",
    adminEmail: "admin@landparcel.com",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "log-2",
    action: "VERIFY_USER",
    details: "Verified Agent credentials for Vikram Singhania (RERA-MH-2023-884920).",
    targetType: "USER",
    targetId: "user-agent-1",
    adminName: "Priya Menon",
    adminEmail: "admin@landparcel.com",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "log-3",
    action: "UPDATE_SETTINGS",
    details: "Updated platform brokerage commission rate to 1.5% with mandatory RERA audit.",
    targetType: "SETTINGS",
    adminName: "Priya Menon",
    adminEmail: "admin@landparcel.com",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    title: "The Grand Azure Waterfront Penthouse",
    description: "Experience unparalleled coastal grandeur atop South Mumbai's most prestigious skyline. This 4BHK triplex penthouse features 360-degree Arabian Sea panoramas, a private temperature-controlled infinity pool on the sky deck, customized Italian marble finishes, smart home automation by Lutron, and exclusive private elevator access. Designed for the discerning connoisseur who demands effortless luxury and privacy.",
    price: 325000000, // 32.5 Cr
    propertyType: "PENTHOUSE",
    listingType: "SALE",
    address: "72 Ocean Crest Promenade, Worli Sea Face, Mumbai, Maharashtra 400018",
    lat: 19.0069,
    lng: 72.8164,
    bedrooms: 4,
    bathrooms: 5,
    areaSqFt: 6200,
    carpetArea: 5450,
    facing: "West",
    parking: 4,
    propertyAge: "Ready to Move",
    maintenanceFee: 45000,
    floor: 42,
    totalFloors: 45,
    furnishingStatus: "FURNISHED",
    status: "APPROVED",
    featured: true,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Private Infinity Pool",
      "Sea View Balcony",
      "Smart Home Automation",
      "Private High-Speed Elevator",
      "Valet Concierge 24/7",
      "Clubhouse & Spa",
      "Helipad Access",
      "EV Charging Stations",
      "Centrally Air Conditioned",
      "Gourmet Modular Kitchen"
    ],
    ownerId: "user-agent-1",
    owner: {
      id: "user-agent-1",
      name: "Vikram Singhania",
      email: "agent@landparcel.com",
      phone: "+91 98200 12345",
      companyName: "Singhania Luxury Estates & Realty",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    },
    createdAt: new Date("2025-01-20").toISOString(),
  },
  {
    id: "prop-2",
    title: "Elysian Palms Portuguese Villa",
    description: "Nestled amidst lush emerald foliage in North Goa, Elysian Palms is a masterfully restored 5BHK luxury estate blending Portuguese heritage architecture with modern Scandinavian minimalism. Features private plunge pool, courtyard fountains, sprawling manicured lawn, outdoor barbecue pavilion, and dedicated staff quarters. Just 8 minutes from pristine Vagator Beach.",
    price: 98000000, // 9.8 Cr
    propertyType: "VILLA",
    listingType: "SALE",   
    address: "Plot 14, Badem Road, Assagao, North Goa 403507",
    lat: 15.5925,
    lng: 73.7661,
    bedrooms: 5,
    bathrooms: 6,
    areaSqFt: 5800,
    carpetArea: 5100,
    facing: "East",
    parking: 3,
    propertyAge: "1-2 Years",
    maintenanceFee: 22000,
    floor: 2,
    totalFloors: 2,
    furnishingStatus: "FURNISHED",
    status: "APPROVED",
    featured: true,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Private Swimming Pool",
      "Landscaped Garden",
      "Outdoor Barbecue Lounge",
      "Solar Power Backup",
      "Servant Quarters",
      "Gated Security 24/7",
      "Bespoke Teak Woodwork",
      "Wine Cellar"
    ],
    ownerId: "user-agent-1",
    owner: {
      id: "user-agent-1",
      name: "Vikram Singhania",
      email: "agent@landparcel.com",
      phone: "+91 98200 12345",
      companyName: "Singhania Luxury Estates & Realty",
    },
    createdAt: new Date("2025-01-25").toISOString(),
  },
  {
    id: "prop-3",
    title: "The Celestia Sky Residency",
    description: "Contemporary 3BHK high-rise apartment situated in the heart of Bengaluru's Silicon Corridor. Boasting expansive floor-to-ceiling soundproof acoustic glass windows, private garden deck, German modular kitchen with built-in Bosch appliances, and smart climate control. Walking distance to international schools and top tech parks.",
    price: 24500000, // 2.45 Cr
    propertyType: "APARTMENT",
    listingType: "SALE",
    
    address: "100ft Road, Defence Colony, Indiranagar, Bengaluru, Karnataka 560038",
    lat: 12.9784,
    lng: 77.6408,
    bedrooms: 3,
    bathrooms: 3,
    areaSqFt: 2450,
    carpetArea: 2120,
    facing: "North-East",
    parking: 2,
    propertyAge: "Under Construction",
    maintenanceFee: 9500,
    floor: 16,
    totalFloors: 28,
    furnishingStatus: "SEMI_FURNISHED",
    status: "APPROVED",
    featured: true,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Olympic Length Swimming Pool",
      "Fully Equipped Gym & Crossfit",
      "Squash & Tennis Courts",
      "Children Play Zone",
      "100% DG Power Backup",
      "Rooftop Stargazing Lounge",
      "Clubhouse & Banquet Hall",
      "EV Car Charging Station"
    ],
    ownerId: "user-agent-1",
    owner: {
      id: "user-agent-1",
      name: "Vikram Singhania",
      email: "agent@landparcel.com",
      phone: "+91 98200 12345",
      companyName: "Singhania Luxury Estates & Realty",
    },
    createdAt: new Date("2025-02-01").toISOString(),
  },
  {
    id: "prop-4",
    title: "CyberOne Commercial Business Hub",
    description: "Grade-A LEED Platinum certified commercial office floor in HITEC City, Hyderabad. Features open-plan flexible floor plates, dedicated VRF HVAC systems, column-free design, 12 high-speed passenger elevators, biometric turnstile security, and 24/7 power backup with dual redundancy.",
    price: 450000, // 4.5 Lakh / month rent
    propertyType: "COMMERCIAL",
    listingType: "RENT",
   
    address: "Tower B, Phase 2, Mindspace Madhapur, HITEC City, Hyderabad 500081",
    lat: 17.4435,
    lng: 78.3772,
    bedrooms: 0,
    bathrooms: 4,
    areaSqFt: 5500,
    carpetArea: 4800,
    facing: "North",
    parking: 8,
    propertyAge: "New Launch",
    maintenanceFee: 35000,
    floor: 8,
    totalFloors: 24,
    furnishingStatus: "FURNISHED",
    status: "APPROVED",
    featured: false,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Grade A Commercial Space",
      "Dual Redundant Power Supply",
      "High-Speed Fiber Connectivity",
      "Conference & Boardrooms",
      "Cafeteria & Food Court",
      "Covered Multi-Level Parking",
      "Fire Safety & Sprinklers",
      "24/7 Biometric Access"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-05").toISOString(),
  },
  {
    id: "prop-5",
    title: "Greenwood Sanctuary Estate Plot",
    description: "Premium clear-title gated residential villa plot in North Bangalore near Kempegowda International Airport. Surrounded by 40 acres of preserved green sanctuary with avenue trees, underground electrical cabling, 40-foot wide asphalted roads, rainwater harvesting network, and grand clubhouse membership included.",
    price: 18500000, // 1.85 Cr
    propertyType: "PLOT",
    listingType: "SALE",
  
    address: "Greenwood Enclave, Near IVC Road, Devanahalli, Bengaluru 562110",
    lat: 13.2458,
    lng: 77.7126,
    bedrooms: 0,
    bathrooms: 0,
    areaSqFt: 4000,
    carpetArea: 4000,
    facing: "East",
    parking: 0,
    propertyAge: "New Launch",
    maintenanceFee: 3000,
    furnishingStatus: "UNFURNISHED",
    status: "APPROVED",
    featured: false,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "BIAAPA & RERA Approved",
      "Underground Drainage & Cabling",
      "40ft Wide Internal Roads",
      "24/7 Gated Perimeter Security",
      "Grand Resort-Style Clubhouse",
      "Lush Landscaped Parks",
      "Dedicated Water Treatment Plant"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-07").toISOString(),
  },
  {
    id: "prop-6",
    title: "The Regency Diplomatic Villa",
    description: "Exquisite 5BHK ultra-luxury bungalow situated on Golf Course Road, Gurugram. Designed by award-winning architects, featuring heated indoor swimming pool, home theater with Dolby Atmos, European designer bath suites, manicured Japanese Zen garden, and private guest wing.",
    price: 185000000,
    propertyType: "VILLA",
    listingType: "SALE",
    address: "Block D, DLF Phase 5, Golf Course Road, Gurugram, Haryana 122002",
    lat: 28.4595,
    lng: 77.0266,
    bedrooms: 5,
    bathrooms: 6,
    areaSqFt: 7500,
    carpetArea: 6800,
    facing: "North-East",
    parking: 4,
    propertyAge: "0-1 Year",
    maintenanceFee: 32000,
    floor: 3,
    totalFloors: 3,
    furnishingStatus: "FURNISHED",
    status: "APPROVED",
    featured: true,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Golf Course Frontage",
      "Indoor Heated Pool",
      "Private Cinema / Dolby Atmos",
      "Gym & Wellness Sauna",
      "Landscaped Zen Garden",
      "Staff & Security Quarters",
      "Solar Energy Integration",
      "Multi-Car Garage with EV Wallbox"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-10").toISOString(),
  },
  {
    id: "prop-7",
    title: "Serenity Heights Lakeview 2BHK",
    description: "Modern, sunlit 2BHK lake-facing apartment in Baner, Pune. Perfect for young families and IT professionals. Close to Hinjawadi IT Park, top schools, and retail centers. Includes modular kitchen, piped gas connection, and designated covered basement parking.",
    price: 8500000, // 85 Lakh
    propertyType: "APARTMENT",
    listingType: "SALE",
    address: "Balewadi High Street Road, Baner, Pune, Maharashtra 411045",
    lat: 18.5596,
    lng: 73.7799,
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1150,
    carpetArea: 950,
    facing: "East",
    parking: 1,
    propertyAge: "Ready to Move",
    maintenanceFee: 3500,
    floor: 7,
    totalFloors: 14,
    furnishingStatus: "SEMI_FURNISHED",
    status: "APPROVED",
    featured: false,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1502005229762-ee1b2da9c5dd?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Lakefront Views",
      "Gymnasium & Yoga Deck",
      "Children Play Arena",
      "24/7 Security & CCTV",
      "Piped Natural Gas (PNG)",
      "Intercom Facility"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-11").toISOString(),
  },
  {
    id: "prop-8",
    title: "Luxury Marina Sea View 3BHK for Rent",
    description: "Spacious fully furnished 3BHK apartment with direct sea views in Bandra West. Steps away from Carter Road promenade, trendy cafes, and boutique dining. Designer lighting, premium Italian furniture, and high-end electronics included.",
    price: 180000, // 1.8 Lakh / month rent
    propertyType: "APARTMENT",
    listingType: "RENT",
    address: "Perry Cross Road, Near Carter Road, Bandra West, Mumbai 400050",
    lat: 19.0596,
    lng: 72.8295,
    bedrooms: 3,
    bathrooms: 3,
    areaSqFt: 1800,
    carpetArea: 1550,
    facing: "West",
    parking: 2,
    propertyAge: "3-5 Years",
    maintenanceFee: 12000,
    floor: 9,
    totalFloors: 16,
    furnishingStatus: "FURNISHED",
    status: "APPROVED",
    featured: true,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Direct Sea View",
      "Fully Furnished with Designer Decor",
      "Covered Stilt Parking",
      "24/7 Building Security",
      "Gym & Fitness Center",
      "Pet Friendly"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-12").toISOString(),
  },
  {
    id: "prop-9",
    title: "Prime Commercial Retail Showroom",
    description: "High-visibility double-height ground floor retail showroom on Main 100ft Road Indiranagar. Unmatched frontage of 45 feet, heavy footfall, glass facade, 3-phase power, and dedicated customer valet parking slots. Ideal for flagship fashion, jewelry, luxury automobile or bank branches.",
    price: 650000, // 6.5 Lakh / month rent
    propertyType: "COMMERCIAL",
    listingType: "RENT",
    address: "Main 100ft Road, Stage 2, Indiranagar, Bengaluru, Karnataka 560008",
    lat: 12.9719,
    lng: 77.6412,
    bedrooms: 0,
    bathrooms: 2,
    areaSqFt: 4200,
    carpetArea: 3900,
    facing: "North",
    parking: 6,
    propertyAge: "Ready to Move",
    maintenanceFee: 25000,
    floor: 1,
    totalFloors: 4,
    furnishingStatus: "UNFURNISHED",
    status: "APPROVED",
    featured: false,
    verified: true,
    images: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "45ft Prime Glass Road Frontage",
      "Double Height Ceiling (18ft)",
      "High Footfall Location",
      "Dedicated Customer Parking",
      "Heavy Power Load 50 kVA",
      "Fire Safety NOC in Place"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-13").toISOString(),
  },
  {
    id: "prop-10",
    title: "Pending Approval: The Palm Springs Duplex",
    description: "Magnificent 4BHK duplex penthouse under moderation review. Modern open layout, double-height living room with Italian chandelier, terrace garden, and smart home provisions.",
    price: 34000000, // 3.4 Cr
    propertyType: "PENTHOUSE",
    listingType: "SALE",
    address: "Road No. 36, Jubilee Hills, Hyderabad 500033",
    lat: 17.4319,
    lng: 78.4073,
    bedrooms: 4,
    bathrooms: 4,
    areaSqFt: 3800,
    carpetArea: 3300,
    facing: "East",
    parking: 3,
    propertyAge: "New Launch",
    maintenanceFee: 14000,
    floor: 11,
    totalFloors: 12,
    furnishingStatus: "SEMI_FURNISHED",
    status: "PENDING", // for admin moderation test
    featured: false,
    verified: false,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85"
    ],
    amenities: [
      "Terrace Garden",
      "Double Height Ceiling",
      "Private Lift Access",
      "Clubhouse Access"
    ],
    ownerId: "user-agent-1",
    createdAt: new Date("2025-02-13T09:00:00Z").toISOString(),
  }
];

export const SAMPLE_INQUIRIES: Inquiry[] = [
  {
    id: "ord-0001234",
    propertyId: "prop-1",
    userId: "user-buyer-1",
    name: "James Witowicky",
    email: "james.witowicky@example.com",
    phone: "+44 20 7946 0912",
    message: "Interested in final closing paperwork and deed transfer verification.",
    visitDate: "2026-04-26",
    visitTime: "12:42 AM",
    visitType: "IN_PERSON",
    status: "PENDING",
    createdAt: new Date("2026-04-26T00:42:00Z").toISOString(),
  },
  {
    id: "ord-0001235",
    propertyId: "prop-2",
    userId: null,
    name: "Stephani",
    email: "stephani.m@example.com",
    phone: "+44 20 8912 3456",
    message: "Counter-offer submitted. Reviewing revised escrow terms with legal counsel.",
    visitDate: "2026-04-26",
    visitTime: "12:42 AM",
    visitType: "VIDEO_CALL",
    status: "PENDING", // used as Negotiation
    createdAt: new Date("2026-04-26T00:42:00Z").toISOString(),
  },
  {
    id: "ord-0001236",
    propertyId: "prop-3",
    userId: null,
    name: "Samantha Jr.",
    email: "samantha.jr@example.com",
    phone: "+1 212 555 0199",
    message: "Awaiting title clearance and environmental audit clearance documentation.",
    visitDate: "2026-04-26",
    visitTime: "12:42 AM",
    visitType: "IN_PERSON",
    status: "PENDING",
    createdAt: new Date("2026-04-26T00:42:00Z").toISOString(),
  },
  {
    id: "ord-0001237",
    propertyId: "prop-4",
    userId: null,
    name: "Hawkins",
    email: "hawkins.realty@example.com",
    phone: "+44 20 7123 4567",
    message: "Negotiation ongoing on lease lock-in period and fit-out rent-free window.",
    visitDate: "2026-04-26",
    visitTime: "12:42 AM",
    visitType: "VIDEO_CALL",
    status: "PENDING",
    createdAt: new Date("2026-04-26T00:42:00Z").toISOString(),
  },
  {
    id: "ord-0001238",
    propertyId: "prop-1",
    userId: "user-buyer-1",
    name: "Aarav Sharma",
    email: "aarav.sharma@landparcel.com",
    phone: "+91 98765 43210",
    message: "Private walkthrough scheduled for penthouse inspection and registry verification.",
    visitDate: "2026-04-28",
    visitTime: "11:00 AM",
    visitType: "IN_PERSON",
    status: "CONFIRMED",
    createdAt: new Date("2026-04-25T14:30:00Z").toISOString(),
  },
  {
    id: "ord-0001239",
    propertyId: "prop-2",
    userId: null,
    name: "Elena Rostova",
    email: "elena.r@luxuryestate.com",
    phone: "+91 98200 99887",
    message: "Full token amount deposited in escrow. Title deed registered successfully.",
    visitDate: "2026-04-20",
    visitTime: "03:00 PM",
    visitType: "IN_PERSON",
    status: "COMPLETED",
    createdAt: new Date("2026-04-20T10:00:00Z").toISOString(),
  },
  {
    id: "ord-0001240",
    propertyId: "prop-4",
    userId: null,
    name: "Rajesh Kulkarni",
    email: "rajesh@techcorp.in",
    phone: "+91 98111 22334",
    message: "Commercial lease agreement drafted for 12,000 sq ft tech hub space.",
    visitDate: "2026-04-22",
    visitTime: "02:30 PM",
    visitType: "IN_PERSON",
    status: "PENDING",
    createdAt: new Date("2026-04-22T08:15:00Z").toISOString(),
  },
  {
    id: "ord-0001241",
    propertyId: "prop-3",
    userId: null,
    name: "David Miller",
    email: "david.m@globex.com",
    phone: "+1 415 889 0012",
    message: "Booking cancellation requested due to overseas corporate relocation.",
    visitDate: "2026-04-18",
    visitTime: "05:00 PM",
    visitType: "VIDEO_CALL",
    status: "CANCELLED",
    createdAt: new Date("2026-04-18T16:20:00Z").toISOString(),
  },
];

export const POPULAR_CITIES = [
  {
    name: "Mumbai",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    propertyCount: "2,450+ Properties",
    tagline: "India's Financial Capital & Waterfront Luxury",
  },
  {
    name: "Bangalore",
    state: "Karnataka",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
    propertyCount: "3,120+ Properties",
    tagline: "Silicon Valley Tech Hub & Garden Living",
  },
  {
    name: "Delhi NCR",
    state: "Delhi / Haryana / UP",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
    propertyCount: "4,200+ Properties",
    tagline: "National Capital Region & Golf Estates",
  },
  {
    name: "Hyderabad",
    state: "Telangana",
    image: "https://images.unsplash.com/photo-1605007493699-ce65834f8a00?auto=format&fit=crop&w=800&q=80",
    propertyCount: "1,890+ Properties",
    tagline: "High-Growth IT Corridors & Gated Villas",
  },
  {
    name: "Pune",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80",
    propertyCount: "1,450+ Properties",
    tagline: "Cultural Capital & Serene Hillside Residences",
  },
  {
    name: "Goa",
    state: "Goa",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    propertyCount: "820+ Properties",
    tagline: "Coastal Retreats, Portuguese Villas & Holiday Homes",
  }
];

export const PROPERTY_CATEGORIES = [
  {
    type: "VILLA",
    name: "Luxury Villas",
    description: "Private sanctuaries with bespoke pools and lush gardens",
    icon: "Home",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=600&q=80",
    count: "480+ Available",
  },
  {
    type: "APARTMENT",
    name: "Modern Apartments",
    description: "High-rise towers with panoramic skyline views and full amenities",
    icon: "Building2",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80",
    count: "1,850+ Available",
  },
  {
    type: "PENTHOUSE",
    name: "Sky Penthouses",
    description: "Exclusive top-floor residences with private terraces",
    icon: "Sparkles",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80",
    count: "120+ Available",
  },
  {
    type: "PLOT",
    name: "Gated Land Parcels",
    description: "Clear-title residential and farm plots in prime growth corridors",
    icon: "Trees",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80",
    count: "650+ Available",
  },
  {
    type: "COMMERCIAL",
    name: "Commercial Spaces",
    description: "Grade-A office suites, tech hubs, and high-street retail",
    icon: "Briefcase",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80",
    count: "340+ Available",
  },
];
